In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv')

In [4]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [5]:
df.tail()

Laptop       Status  Brand  \
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished  Razer   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished  Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished  Razer   
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished  Razer   
2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished  Razer   

      Model                CPU  RAM  Storage Storage type       GPU  Screen  \
2155  Blade      Intel Core i7   16     1000          SSD  RTX 3060    17.3   
2156  Blade      Intel Core i7   16     1000          SSD  RTX 3070    17.3   
2157  Blade      Intel Core i7   32     1000          SSD  RTX 3080    17.3   
2158   Book  Intel Evo Core i7   16     1000          SSD       NaN    13.4   
2159   Book  Intel Evo Core i7   16      256          SSD       NaN    13.4   

     Touch  Final Price  
2155    No      2699.99  
2156    No      2899.99  
2157    No      3399.99  
2158   Yes      1899.99  
2159   Yes      1699.99

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(4)

array([1., 1., 1., 1.])

In [6]:
np.full(10,6.7)

array([6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7])